services:
    contao_manager.plugin_loader:
        class: Contao\ManagerBundle\ContaoManager\PluginLoader
        synthetic: true

    contao_manager.routing_loader:
        class: Contao\ManagerBundle\Routing\RouteLoader
        arguments:
            - "@routing.loader"
            - "@contao_manager.plugin_loader"
            - "@kernel"
